const SLIDER_IS_CREATED = 'SLIDER_IS_CREATED';
const EVENT_TRIGGERED = 'EVENT_TRIGGERED';
const RECRATE_APP = 'RECRATE_APP';
const HORIZONTAL_SLIDER = 'horizontal';
const VERTICAL_SLIDER = 'vertical'

export {
  SLIDER_IS_CREATED,
  EVENT_TRIGGERED,
  RECRATE_APP,
  HORIZONTAL_SLIDER,
  VERTICAL_SLIDER
}